# Holds the UI which is a frontend Angular application
moira-nginx:
  build: web
  links:
    - moira-api:moira-api
  volumes:
    - ./config/yaml:/etc/moira/
    - ./config/json:/var/local/www/moira/config/
  ports:
    - 8080:8080

# Cache is a lightweight Go application responsible for receiving lots of metric data in Graphite format. 
# Cache filters received data and saves only metrics that match any of user triggers. 
# This reduces load on all other parts of Moira.
moira-cache:
  build: moira-go/
  links:
   - redis:redis
  command: "/moira/bin/cache --config=/etc/moira/config.yml"
  volumes:
    - ./config/yaml:/etc/moira/
  ports:
    - 2003:2003
    - 2003:2003/udp

# Notifier is a Go application that watches for generated events. 
# Notifier is responsible for scheduling and sending notifications, 
# observing quiet hours, retrying failed notifications, etc.


moira-notifier:
  build: moira-go/
  links:
   - redis:redis
  command: "/moira/bin/notifier --config=/etc/moira/config.yml"
  volumes:
    - ./config/yaml:/etc/moira/

# API is a Python application that serves as a backend for UI.
moira-api:
  build: moira-pip/
  links:
   - redis:redis
  command: moira-api
  volumes:
    - ./config/yaml:/etc/moira/
    - ./config/json:/var/local/www/moira/
  expose:
    - 8081

# Checker is a Python application with embedded Graphite functions. 
# Checker watches for incoming metric values and performs checks 
# according to saved trigger settings. 
# When state of any trigger changes, Checker generates an event.
moira-checker:
  build: moira-pip/
  links:
   - redis:redis
  command: moira-checker
  volumes:
    - ./config/yaml:/etc/moira/

# A Redis database ... 
redis:
  image: redis
  expose:
   - 6379
